// backend/utils/constants.js

const PROPOSTA_CONTRATO_STATUS = Object.freeze({
  EM_ELABORACAO: "Em Elaboração",
  AGUARDANDO_APROVACOES: "Aguardando Aprovações",
  AGUARDANDO_ASSINATURA_CLIENTE: "Aguardando Assinatura Cliente",
  ASSINADO: "Assinado",
  VENDIDO: "Vendido",
  RECUSADO: "Recusado",
  CANCELADO: "Cancelado",
  DISTRATO_REALIZADO: "Distrato Realizado",
});

const LEAD_HISTORY_ACTIONS = Object.freeze({
  CRIACAO: "CRIACAO",
  ATUALIZACAO: "ATUALIZACAO", // Generic update, might be too broad. Specific updates are better.
  EDICAO_DADOS: "EDICAO_DADOS", // More specific than ATUALIZACAO for general field edits
  DESCARTE: "DESCARTE",
  REATIVACAO: "REATIVACAO",
  RESERVA_CRIADA: "RESERVA_CRIADA",
  RESERVA_CANCELADA: "RESERVA_CANCELADA",
  RESERVA_EXPIRADA: "RESERVA_EXPIRADA",
  PROPOSTA_CONTRATO_CRIADA: "PROPOSTA_CONTRATO_CRIADA",
  PROPOSTA_CONTRATO_EDITADA: "PROPOSTA_CONTRATO_EDITADA",
  // Specific proposal status changes for more granular history
  PROPOSTA_STATUS_EM_ELABORACAO: "PROPOSTA_STATUS_EM_ELABORACAO",
  PROPOSTA_STATUS_AGUARDANDO_APROVACOES: "PROPOSTA_STATUS_AGUARDANDO_APROVAÇÕES",
  PROPOSTA_STATUS_AGUARDANDO_ASSINATURA_CLIENTE: "PROPOSTA_STATUS_AGUARDANDO_ASSINATURA_CLIENTE",
  PROPOSTA_STATUS_ASSINADO: "PROPOSTA_STATUS_ASSINADO",
  PROPOSTA_STATUS_VENDIDO: "PROPOSTA_STATUS_VENDIDO",
  PROPOSTA_STATUS_RECUSADO: "PROPOSTA_STATUS_RECUSADO",
  PROPOSTA_STATUS_CANCELADO: "PROPOSTA_STATUS_CANCELADO",
  PROPOSTA_STATUS_DISTRATO_REALIZADO: "PROPOSTA_STATUS_DISTRATO_REALIZADO",

  // General status change if specific ones are too many, but specific is often better for audit.
  // PROPOSTA_STATUS_ALTERADO: "PROPOSTA_STATUS_ALTERADO",

  VENDA_CONCRETIZADA: "VENDA_CONCRETIZADA", // Could be redundant if PROPOSTA_STATUS_VENDIDO implies this.
  DISTRATO_REALIZADO_HIST: "DISTRATO_REALIZADO", // Name conflict with Proposta status, hence HIST
  UNIDADE_LIBERADA: "UNIDADE_LIBERADA",
});

const LEAD_STAGE_NOME_EM_RESERVA = "Em Reserva";
const LEAD_STAGE_NOME_PROPOSTA_EMITIDA = "Proposta Emitida";
const LEAD_STAGE_NOME_VENDA_REALIZADA = "Venda Realizada";
const LEAD_STAGE_NOME_PROPOSTA_RECUSADA = "Proposta Recusada";
const LEAD_STAGE_NOME_NEGOCIACAO_PERDIDA = "Negociação Perdida";
const LEAD_STAGE_NOME_DESCARTADO = "Descartado";
const LEAD_STAGE_NOME_DISTRATO_CONTRATUAL = "Distrato Contratual"; // For Lead when a contract is voided

const RESERVA_STATUS = Object.freeze({
    ATIVA: "Ativa",
    EXPIRADA: "Expirada",
    CANCELADA: "Cancelada",
    CONVERTIDA_EM_PROPOSTA: "ConvertidaEmProposta",
    CONVERTIDA_EM_VENDA: "ConvertidaEmVenda",
    RECUSADA_PELA_PROPOSTA: "RecusadaPelaProposta",
    CANCELADA_PELA_PROPOSTA: "CanceladaPelaProposta",
    DISTRATADA: "Distratada",
});

const UNIDADE_STATUS = Object.freeze({
    DISPONIVEL: "Disponível",
    RESERVADA: "Reservada",
    PROPOSTA: "Proposta",
    VENDIDO: "Vendido",
    BLOQUEADO: "Bloqueado",
});


module.exports = {
  PROPOSTA_CONTRATO_STATUS,
  LEAD_HISTORY_ACTIONS,
  LEAD_STAGE_NOME_EM_RESERVA,
  LEAD_STAGE_NOME_PROPOSTA_EMITIDA,
  LEAD_STAGE_NOME_VENDA_REALIZADA,
  LEAD_STAGE_NOME_PROPOSTA_RECUSADA,
  LEAD_STAGE_NOME_NEGOCIACAO_PERDIDA,
  LEAD_STAGE_NOME_DESCARTADO,
  LEAD_STAGE_NOME_DISTRATO_CONTRATUAL,
  RESERVA_STATUS,
  UNIDADE_STATUS,
};
